### ISSUE TITLE
UI Bugs - Textbox Fields

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1036]
**No cut, copy, paste**
- Cannot cut, copy, or paste text in **any** textboxes
- Tis standard function for any modern textbox
- Tis a must have for game development

**Tooltips**
Tooltips on textboxes is just annoying :)
- Better to use hint text in control itself (modern feature)

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by michaeloldman** [comment]
Build 2021.02.04 - Exhibits same issue :)
- Cut, copy, paste - still missing
- OFF switch required tooltips - very annoying....

**Comment by plemsoft** [comment]
@michaeloldman Thanks for reporting this issue, just tested and copy/paste works fine here for all textboxes ?

Only thing is, in a value field you can only paste digits, in normal textboxes you can copy/paste anything.

Is this somewhere special you try to paste ? :)

@rvanner About the tooltips on "textboxes" should we do this as a preference setting, or you got another idea ? , perhaps also add it as a new feature request :)

**Comment by rvanner** [comment]
@plemsoft Yes, we need another settings tick box to deal with this. I will make a new task for it on Teamwork.

**Comment by plemsoft** [comment]
@rvanner Setting tick box, added. Could you also validate that copy/paste in text boxes works for you in the latest version, thanks :)

**Comment by rvanner** [comment]
@plemsoft The cut & paste works in some places. If you drag in a TEXT object and then type some text into the PROMPTEXT box on the right, then cut that text, the object tools menu disappears

**Comment by plemsoft** [comment]
@rvanner Ahh i see it now, if you have a object selected and are using the textbox copy/paste it also copy/paste the selected object , I have now protected all text input fields so copy/paste only goes to them while they are active. Everything here should be fixed now :)

**Comment by rvanner** [comment]
OK! I'll give it a full test when I get a new build.

**Comment by rvanner** [comment]
@plemsoft Still happens in latest build. Video of it happening is here;
https://youtu.be/kERU_oduL0w

**Comment by plemsoft** [comment]
@rvanner Ups only Copy/Paste was protected from this, now Cut is also protected :) , ready from next update.

**Comment by michaeloldman** [comment]
@plemsoft 
For me text boxes seam to work fine (not tried them all tho)
- So Ctrl+X cuts, Ctrl+C copies, Ctrl+V pastes.
However sometimes non-compliant shortcuts, example Crtl+Z, will just delete the object.
To me it would be useful to have RMB context menu options available as well.

Also noticed in latest build we can **turn off help tooltips for edit fields** - that is great addition.
It would be nice to be able to turn **all tooltips off**
- Because they popup instantly they are just an annoyance
- - and don't provide any more info than what is already shown by the UI anyway
- or provide a delay value so we can set it to higher value (like 60 seconds) where it is unlikely to popup

:)

**Comment by rvanner** [comment]
I will close this issue but I'l make a note to add a turn off all help boxes - it will be a low priority for now but we will get to it at some point.
