### ISSUE TITLE
Weapons Pack update today some textures not multiple of 2 size

### ISSUE THREAD

**Issue by Pirate-Myke** [TheGameCreators/GameGuruRepo#114]
Lead Pipe
gun_gloss 2065 x 2048
gun_n 2107 x 2048
gun_normal 2107 x 2048

BaseBall Bat
gun_gloss 2065 x 2048

**Comment by LeeBamberTGC** [comment]
Fixed in latest beta :)

**Comment by Pirate-Myke** [comment]
Thank you.

**Comment by GraPhiX-Guru** [comment]
Are the BETA's still being pushed through steam? i have not seen a BETA build since PP2 or do we have to download it manually ?

**Comment by Pirate-Myke** [comment]
I am still receiving beta build updates. That's how I received the weapons pack.

**Comment by GraPhiX-Guru** [comment]
ummmm i don't seem to be getting them that's odd

**Comment by Pirate-Myke** [comment]
See if auto update is turns on for the beta and not the public preview.

**Comment by GraPhiX-Guru** [comment]
it is turned on :( in my steam library it says GameGuru (beta) but the version is 2018.02.xx DX11 Preview

**Comment by Pirate-Myke** [comment]
That is what it reports for me also when I start it up.

After each update, I go thru the folders to see what has been changed.

Weapons pack pickups and guns folders where new. The exe also had a newer date.

**Comment by GraPhiX-Guru** [comment]
i am validating again now 4th time today, i thought it was strange i have not been getting updates, if this does not work i will delete my GG folder and download again

**Comment by Pirate-Myke** [comment]
What I did not check was the weapon pickup texture sizes yet.

**Comment by GraPhiX-Guru** [comment]
looks like i have been testing all my models on the wrong version if i don't have the latest beta :(

**Comment by GraPhiX-Guru** [comment]
Nope no joy i will uninstall and apply my beta key again see if it downloads the latest version

**Comment by GraPhiX-Guru** [comment]
ive made a post in beta section of forum I did not mean to derail your thread sorry
