### ISSUE TITLE
GG Max - Bug - Building walls disappear

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2748]
I have kept trying to place a Structure - House, But after placing the object, then moving away and doing something else like adding another item, then moving back to it, some of the walls seem to go see through, and disappear.
You can see in the first 2 images the walls are there, and the next images some walls have disappeared.

![image](https://user-images.githubusercontent.com/66874403/161537522-99d9c36d-26f7-44d1-998b-aad39cb47112.png)

![image](https://user-images.githubusercontent.com/66874403/161537616-e82ee5fb-5abb-42b3-91e7-8a383692d516.png)

![image](https://user-images.githubusercontent.com/66874403/161537863-f20431c5-20d4-429e-83b5-a3458513b542.png)

![image](https://user-images.githubusercontent.com/66874403/161537910-ae854637-a2a5-4ee4-a96c-b8ef04b48f7a.png)

**Comment by dllllllllllb** [comment]
Some more information: https://www.youtube.com/watch?v=PrHEilQ1pnI

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Tum1370** [comment]
This is still not fixed in the latest version of Max, Friday 8th April.

**Comment by Tum1370** [comment]
@plemsoft 
Yes for some reason that model on my map did not have double sided ticked. After ticking that it was working fine. Not sure why that happened as i dont go anywhere near the materials tab.

Thanks

**Comment by Tum1370** [comment]
@plemsoft 
Hi again, After retesting this structure, even with double sided ticked, The walls and ceilings are still missing.

![image](https://user-images.githubusercontent.com/66874403/162566286-de680fe9-a5ac-4a45-9e0e-0fdb32438a01.png)

**Comment by plemsoft** [comment]
@Tum1370 You need to set double sided on both meshes :)

**Comment by Tum1370** [comment]
@plemsoft 
LOL sorry, didnt even know had different meshes, Thanks that worked.
