### ISSUE TITLE
Internal 04.22 : Lights Flickering & Mega FPS Drop

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#2921]
Latest Build Internal Build - 2022.04.22

https://www.youtube.com/watch?v=zScYmWpoFLI

Drop a light into a scene and deselect the light and the Light Element (the icon for the light) will start flickering like crazy. 
The light itself does not flicker but if the light is hitting any object with Transparency then that object will start flickering as well. 

This causes levels with lights to to be near unusable. In this video I have like 7-8 FPS.  Last night on same level I had about 90 fps so yea this one pretty nasty.  

EDIT* - This may be caused by having Transparent Shadows enabled. 
This can be reproduced by going to a new scene and copying and pasting 10 or more point lights (maybe make sure some of these lights overlap? - not sure about this one). Next set Light Shadow Resolution to 2048. And then enable Transparent Shadows. You should see massive drops of FPS.

**Comment by Kitakazi** [comment]
Turning off Transparent Shadows does NOT fix the lights flickering. But it does fix the FPS drop

**Comment by ArgentArts** [comment]
I have the latest experimental build and cannot reproduce this. I placed 10+ point lights in a scene, set their shadow resolution to 2048, and ticked the Transparent Shadow box. There was no flickering in the editor and movement was smooth. I could also run the level with no frame drops.

**Comment by plemsoft** [comment]
@LeeBamberTGC This is the flickering problem, see video.

**Comment by LeeBamberTGC** [comment]
@plemsoft Do you want to have a go at reverting the two commits you shouwed me thtn you think might solve it and see if it goes away for you?

**Comment by plemsoft** [comment]
@LeeBamberTGC Committed to my wicked branch , ready to merge , its now in a define and not active for now, fix the flickering :)

**Comment by LeeBamberTGC** [comment]
Fixed for latest Steam build, will be in Fridays release.

**Comment by Kitakazi** [comment]
The flickering is gone but I still have bad performance with Transparent Shadows enabled now. 
Same FPS as in the video.

**Comment by plemsoft** [comment]
@Kitakazi That is a extreme fps drop, sounds like the GPU is swapping textures in and out all the time, could you try to go to the shadows settings and lowering the resolution for the different shadows types and see if that fix the issue , thanks for your help :)

**Comment by Kitakazi** [comment]
@plemsoft 
Lowering the shadow resolution on the point-light helps the issue. But something is still wrong, the build last week was running really smooth, on same level I had point/spot light shadows at 2048, transparent shadows, running at 90+ fps.  Transparent shadows off it was running easily 130 fps+

Now, with Transparent Shadows turned OFF. I set point light shadow to 1024 and the scene will randomly go from 60 fps  to 30fps. If I turn the shadow res to 2048, its bad. FPS drops down to the teens. This is all with Transparent Shadows Off.  Currently while trying to test for this reply my FPS have dropped under 1 and doesnt look like they will make it back above 1. 
![image](https://user-images.githubusercontent.com/51464873/164992995-3eb242a1-05d5-49c6-b0c5-4ac8ef6a4d84.png)

**Comment by plemsoft** [comment]
@Kitakazi Strange perhaps you added another point light to the level? remember 1 point light use 6 textures and render the scene 6 times more each frame.

I checked the code and dont see any changes that could result in such a difference:

Just to make sure , could you use the "GameGuru MAX Updater.exe" and install the "2022.04.08" version and let me know if you still see this huge difference, or you just added a few more light to the level (When it comes to a GPU swapping issue, just added 1 or 2 more could make all the difference).

Or zip up a standalone of this level so im able to test it and e-mail a download link to plemsoft@plemsoft.com

Thanks for your help :)

**Comment by Kitakazi** [comment]
@plemsoft 
After downloading the new update that came out today it looks to be fixed lol.
Running same level with 2048 shadows and transparent shadows enabled at 60+ fps no problem now.
