### ISSUE TITLE
f11 metalness gloss textures

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#357]
Hi again,

When a project is saved standalone and opened you can see the fps counter by pressing f11 as we all know right? The problem after pressing f11 when you press 1, 2, 3 ... 9 from the keyboard as if you are switching between weapons you can see the albedo, normals, metalness, gloss and ao textures in-game. 

PS: it will still happen even if you disable f11 FPS counter from the setup.ini file 
PS2: Is there a way to set as default any of these texture effects on a standalone game

**Comment by sfkylcnky** [comment]
Hi Lee

Is there a way to set as default any of these texture effects on a standalone game?

**Comment by LeeBamberTGC** [comment]
The only way would be to hack the pbr shader to use your own final render output code, but rememeber to keep a backup of it, or better, create your own apbr_core.fx shader and reference that, then you have full control over what your game renders.

**Comment by sfkylcnky** [comment]
Hi Lee,

Since this issue is closed I think the problem is solved. I have installed the 2018.11.26 update. The only difference in the setup.ini regarding the older version is the reloadweapongunspecs=0 line. I am not sure if this is related with this problem. However it is said in the [update](https://www.thegamecreators.com/post/gameguru-november-update-released) review that: 

> The F11 mode to view PBR texture stages can now be disabled in the SETUP file of the standalone executable for the final shippable title. In addition to the above improvements to retaining model textures, we have also fixed the issue of incorrect FOV when modifying it within the game via a script.

Hence I presume that it can be disabled through the setup.ini but i couldn't find how. Need your help on this situation to disable F11 mode in standalone games via setup.ini. How can we disable it and from where do we do it.

Much appreciated.

**Comment by LeeBamberTGC** [comment]
For reference, the SETUP INI file flag to use to disable F11 PBR debugging is the field:

profileinstandalone=1

Which when set to zero will not use the debug PBR view when F11 is pressed.

**Comment by sfkylcnky** [comment]
Tried and didn't succeed sadly. Visuals still showing up after pressing f11 whether or not profileinstandalone line is 1 or 0 it doesn't seem to matter.

**Comment by Pirate-Myke** [comment]
I am still seeing this behavior when I press F11 in stand alone build.
with either setting in the standalone build setup.ini file at
profileinstandalone=1
or
profileinstandalone=0

game guru setup.ini for the editor uses profileinstandalone=0

**Comment by LeeBamberTGC** [comment]
Was missing condition in game play script, sorted for next build.
