### ISSUE TITLE
Game Guru Max Bug Save and Load level.

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4275]
I did some tests with a test map and I noticed that Game Guru Max doesn't save the things added in the map

**Comment by davetgc** [comment]
As you saying nothing is saved? I've not seen this, and I've not heard of the issue before..

Can you supply some more information, ideally a video.

**Comment by davetgc** [comment]
Confirmed, saving a test level doesn't save any of the work and clears the map.

**Comment by LeeBamberTGC** [comment]
@SampeyFS @davetgc I assume you mean adding an object into the level editor and then saving and reloading. All works well here and I would have expected a lot more reports if this fundamental feature was broken. Can you send me a small video showing the effect, thanks!

**Comment by LeeBamberTGC** [comment]
@davetgc Try now with the latest EXP. Ensure any rogue tab-delimited files are deleted from the project folder.

**Comment by SampeyFS** [comment]
Exactly so it makes me add one thing I started the program or even without restarting it disappears the thing or the function I put

**Comment by LeeBamberTGC** [comment]
@SampeyFS Latest EXP build tested with a fresh game project and the DLC level, and works nicely now:
![image](https://user-images.githubusercontent.com/35840583/227276941-558974cc-f645-4cc9-b9c5-571bb9f1ac2a.png)

**Comment by SampeyFS** [comment]
it doesn't work for me it doesn't save the things I put the removes I put the game with the particle or turned it off I reloaded everything disappeared

**Comment by SampeyFS** [comment]
it doesn't work for me it doesn't save the things I put the removes I put the game with the particle or turned it off I reloaded everything disappeared

**Comment by LeeBamberTGC** [comment]
@SampeyFS Try with a newly created game project, then when it fails to load your level objectrs, zip up the project folder you created from the writable and email it to me at lee@thegamecreators.com
Thanks!

**Comment by SampeyFS** [comment]
![image](https://user-images.githubusercontent.com/108415264/227282496-a7e96c1c-37bc-43f9-9d92-9710ab35c5ee.png)
Now it saves but doesn't save wood icons at the shop this la did when I exited and reloaded the program disappeared the icons but even when cera didn't work there was the usual box

**Comment by SampeyFS** [comment]
OK sir I sent you an email with a question

**Comment by plemsoft** [comment]
@LeeBamberTGC FYI: Think there are more issues in here , i got the same today could not save. i fixed that problem it was if iEntitiesToSaveCount==0 then the map.ele was saved inside: projectbank/name/collection - items.ele , i commit a fix for it later today :)

**Comment by SampeyFS** [comment]
Think there are more issues in here , i got the same today could not save. i fixed that problem it was if iEntitiesToSaveCount==0 then the map.ele was saved inside: projectbank/name/collection - items.ele , i commit a fix for it later today :)


Da: Preben ***@***.***>
Inviato: venerdì 24 marzo 2023 11:47
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] Game Guru Max Bug Save and Load level. (Issue #4275)


@LeeBamberTGC<https://github.com/LeeBamberTGC> FYI: Think there are more issues in here , i got the same today could not save. i fixed that problem it was if iEntitiesToSaveCount==0 then the map.ele was saved inside: projectbank/name/collection - items.ele , i commit a fix for it later today :)

**Comment by SampeyFS** [comment]
eh yes seen I was right it doesn't save by chance there are weapons like bow and arrow? xké I tried the one from Game Guru Classic don't go I convert it also the lua but it doesn't work


Da: Preben ***@***.***>
Inviato: venerdì 24 marzo 2023 11:47
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] Game Guru Max Bug Save and Load level. (Issue #4275)


@LeeBamberTGC<https://github.com/LeeBamberTGC> FYI: Think there are more issues in here , i got the same today could not save. i fixed that problem it was if iEntitiesToSaveCount==0 then the map.ele was saved inside: projectbank/name/collection - items.ele , i commit a fix for it later today :)

**Comment by SampeyFS** [comment]
eh yes seen I was right it doesn't save by chance there are weapons like bow and arrow? xké I tried the one from Game Guru Classic don't go I convert it also the lua but it doesn't work

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Preben ***@***.***>
Inviato: venerdì 24 marzo 2023 11:47
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] Game Guru Max Bug Save and Load level. (Issue #4275)


@LeeBamberTGC<https://github.com/LeeBamberTGC> FYI: Think there are more issues in here , i got the same today could not save. i fixed that problem it was if iEntitiesToSaveCount==0 then the map.ele was saved inside: projectbank/name/collection - items.ele , i commit a fix for it later today :)

**Comment by davetgc** [comment]
This is still an issue for me at present. I'll test when the next experimental build goes live, as I'm guessing the fix isn't up yet.

**Comment by davetgc** [comment]
@SampeyFS - "eh yes seen I was right it doesn't save by chance there are weapons like bow and arrow? xké I tried the one from Game Guru Classic don't go I convert it also the lua but it doesn't work"

Please keep each post on topic, if you have questions not about a posted issue, the best place to ask is the GameGuru MAX discord.  - Thanks.

**Comment by davetgc** [comment]
#4275

**Comment by davetgc** [comment]
#4308

**Comment by davetgc** [comment]
This still isn't working for me I'm afraid.

**Comment by plemsoft** [comment]
@davetgc The "save game" issue has not be merged yet, so will first be in the next EXP build :)

**Comment by davetgc** [comment]
@plemsoft - Well, that explains it :)
