### ISSUE TITLE
GG MAX - Cursor is not visible on screen about

### ISSUE THREAD

**Issue by blackhat110** [TheGameCreators/GameGuruRepo#4397]
The cursor is not visible on the about screen. My specs are: 10th gen intel core i7, nvidia geforce rtx 2060 and 32GB RAM.

**Comment by plemsoft** [comment]
@blackhat110 This was fixed this week , please update to the latest EXP build, and give it another try :)

**Comment by blackhat110** [comment]
@plemsoft still not working

**Comment by plemsoft** [comment]
@blackhat110 How are you testing ? , if its from a standalone you need to export the standalone again using the latest build :)

**Comment by blackhat110** [comment]
@plemsoft here's what i did: re-created the standalone game. You know what happened? it still does not work! :)

**Comment by blackhat110** [comment]
I checked the version I have on Steam and it is the March 9th version, is this the correct version?

**Comment by plemsoft** [comment]
@blackhat110 No its not in that version , only in the latest EXP Build. There is a few annoying bug in the current EXP build ( flickering ) , so perhaps wait until the Wednesday EXP build to try it out :)
