### ISSUE TITLE
GG Max - EXP - BUG - Splash Screen does NOT show on a Standalone

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4495]
As the title says, After creating a Standalone, The Splash Screen does not show when you load the Standalone.

**Comment by plemsoft** [comment]
@Tum1370 Thanks for reporting this issue, this has been fixed and will be in the next EXP build :)

**Comment by Tum1370** [comment]
@plemsoft Sorry but this is not fixed in latest EXP build.

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft i cannot send it..
It is a small level I made, several character created enemy. A couple of downloaded items. First Aid box. And Body Armour. 

All working fine,, and all worked fine in standalone prior to latest exp download today. 
only thing that didn’t work was the splash screen. 

Now on that standalone all I get is that message you see, then the game loads in, and works fine.

**Comment by Tum1370** [comment]
Clearly looking at that error message it is something to do with encryption.

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft 
I think i have now figure out what is causing my encrypted image for the splash screen.
I use the SAME image for the TITLE SCREEN as well. Maybe thats why it is encrypted ??

So i tried a totally different image, I DI NOT get a splash screen showing up, but i also DID NOT get the encryption message.

So for me, this is still not fixed

**Comment by plemsoft** [comment]
@Tum1370 Thanks fixed for the next EXP update :)

**Comment by Tum1370** [comment]
@plemsoft Has this actually gone in to the latest exp build today ? Because for me. Still no splash screen on a real standalone. 

If I test a Standalone from using the STORYBOARD TEST STANDALONE. The splash screen works.

**Comment by LeeBamberTGC** [comment]
@plemsoft Turns out it was not an encryption issue, simply the splash file was not copied over from the game project assets. Sorted this for the next EXP build.

**Comment by LeeBamberTGC** [comment]
@Tum1370 When you see in next EXP build, it means the next build after the date stamp on this issues board. If you read in the current EXP build, it means the one available right now.

**Comment by Tum1370** [comment]
@LeeBamberTGC @plemsoft 

> @Tum1370 When you see in next EXP build, it means the next build after the date stamp on this issues board. If you read in the current EXP build, it means the one available right now.

Ye i only ever check now after seeing an email stating the fix, then checking when steam updates Max.

I can now confirm that Splash screens show in a Standalone game. Thanks for the fix, Ill close this issue now.
