### ISSUE TITLE
transparent textures on custom entity media

### ISSUE THREAD

**Issue by bonesy23438** [TheGameCreators/GameGuruRepo#548]
when using custom textured characters and adding a decal the custom entity becomes transparent
![Desktop Screenshot 2019 06 19 - 08 47 35 01](https://user-images.githubusercontent.com/37757086/59792224-922dc400-92cb-11e9-9a62-846a1c8fd184.png)
![Desktop Screenshot 2019 06 19 - 09 22 40 06](https://user-images.githubusercontent.com/37757086/59792225-922dc400-92cb-11e9-87b4-839e52cd737c.png)

**Comment by plemsoft** [comment]
@bonesy23438 Thanks for reporting this,

This has been fixed and are ready from the next update.

**Comment by plemsoft** [comment]
@bonesy23438 Could you test this in 2019.06.20 and let me know if it works :)

The new beta should be available now.

**Comment by bonesy23438** [comment]
Hi Preben,
have done a test and still got issue it happens as soon as i add a decal
custom or even stock media.Ive even converted the textures on the enitites
to .dds format and tested again and still the same,im using dxt1
compression and genrate mipmaps.It seems to happen in front of the models
ive textured and after i pass a certain spot or die before i get to the
point where it seems to happen,but it seems to be in front of models with
custom textures.The custom textures are png.The fx shader on custom
character entities is character basic,the fx shader for custom models is
apbr_basic.
Thanks Andy

**Comment by plemsoft** [comment]
@bonesy23438 Thanks this is in 2019.06.20 , and you say that you need to die. Also do you use spawn ?
I will have another look :)

**Comment by plemsoft** [comment]
@bonesy23438 Tried to reproduce this in a level , with no luck.

Can you confirm you tested this in 2019.06.20 ?

Could you try to place the player marker in the area in the above screenshot , and check if this generate the above issue when you die.

If so could you try to make a small fpm perhaps at the same point as in your screenshot above, zip it and email it to me at plemsoft@plemsoft.com so i can test it :)

**Comment by bonesy23438** [comment]
Hi Preben,
Have done another test,when you mentioned spawn im spawning the entities
in,but at the start im not spawning the first batch of character
entities,as soon as i hit the first trigger zone and spawn the second batch
in thats when the bug happens,so i set the second batch of entities to
spawn at start,and the bug dissappeared.Out of curiosity does mixing
spawning entities ie spawn at start = yes then spawning entities in
afterwards with spawn at start = no cause a problem.Do you have to spawn
all entities as either spawn at start = yes or spawn at start = no?
Thanks Andy

**Comment by bonesy23438** [comment]
hi Preben,
I have the level already zipped up and uploaded but it is about 5gb big i
have tried to include all media
https://drive.google.com/file/d/1gyTsZXnQqiicvzSnUWOlOG3PaZEwqqoV/view?usp=sharing
thanks Andy

**Comment by bonesy23438** [comment]
Hi Preben,
Also i noticed that id got the character enitities with the spawn at start
= yes had the same naming as the spawning start = no character entities and
i spawned them in on the second trigger zone.
Thanks Andy

**Comment by plemsoft** [comment]
@bonesy23438 It should not matter when or how you spawn.

(Also you tested a special test version and confirmed it worked so , thanks for the help )

This was fixed and are ready from the next update :)
