### ISSUE TITLE
GGMAX Bug - Inventory scrollbar handle

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5538]
inventory full as you can see it doesn't go below the scrollbar doesn't work

![Screenshot 2024-05-12 223600](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7b0657d9-02c5-433c-97cd-b3acc03941a2)
![Screenshot 2024-05-12 223708](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/505b903f-350b-421d-90e0-d48edfba1cb4)

**Comment by Necrym59** [comment]
I cant see your inventory Scrollbar Handle in your images?
![inventory](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/9c06d701-53f5-4153-8044-3d52a099b15d)

**Comment by SampeyFS** [comment]
Yes, what I say doesn't work

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/b23f3bd6-4822-4093-8246-0516ef83cd49)
not work

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/fd461d4d-8dba-4a70-8f7f-36755c6010a8)

**Comment by Necrym59** [comment]
Ive just tested it and it does work. Dont know what your problem is but its not the scroll bar. I still dont see any scrollbar handles on your hud perhaps delete them and put new ones in.

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-14 084845](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/9b28a8e9-8cea-4e64-bc8c-c4e7e8a275ad)
it doesn't work here either

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-14 085519](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a34f84f5-bdb0-47d0-ab14-02ece489687e)
I reset as you say but nothing works

**Comment by Necrym59** [comment]
Ive just tested it and it does work. 
I still dont see any scrollbar handles on your hud perhaps delete the inventory box and do new ones again.
Show the hud screen of the inventory and also the final in game screen if the same inventory.

**Comment by SampeyFS** [comment]
it was already selected and removed but it doesn't work

**Comment by Necrym59** [comment]
**Why do you have the 'Hide Image In Game' ticked?? for the Scrollbar handle!!**

**Comment by SampeyFS** [comment]
it selects itself I had removed the hide it is back on (by itself)

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-14 090850](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/72c2dd1c-2e9d-4cf6-8e56-129deea6708a)

he was selected he put himself back on and went below as you see he was above

**Comment by Necrym59** [comment]
Try turning it off then save your project. Then restart MAX.
If that fails then you have a corrupted hud i suspect, you may have to would delete it and remake it

**Comment by SampeyFS** [comment]
I tried to put the project back into a new one but nothing works it hides itself

**Comment by Necrym59** [comment]
Sound like somthing is corrupted you may have to veriufy or reinstall Max

**Comment by SampeyFS** [comment]
OK I'll try and see

**Comment by SampeyFS** [comment]
they are resources, I didn't want to make a small field of wheat but plant a plant just like I do to make many grow @Necrym59

**Comment by SampeyFS** [comment]
Nothing doesn't work, I uninstalled and reinstalled max but the empty map bar doesn't work

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/2946f6ec-ace7-4c1a-a9e0-29526472b80b)
Original blank map is already hidden as you can see and it doesn't work


@LeeBamberTGC

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-14 131221](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/785e27b8-9150-445f-807e-23ca67d7b964)
RPG Template scrollbar not word

**Comment by SampeyFS** [comment]
https://www.youtube.com/watch?v=FSr5GDwA3qA  @LeeBamberTGC

**Comment by Necrym59** [comment]
Excellent video and screenshots of the problem i will flag this one for Lee

**Comment by SampeyFS** [comment]
Thanks friend, I wanted to ask you with Resource node, I wanted to grow a small field of wheat but I'm worried about just one plant, how can I make it grow, thanks for the reply

**Comment by Necrym59** [comment]
@SampeyFS 
The resouce node will respawn an entity multiple times but you have to have a few of them one for each respawnable entity
so make 1 node then copy and paste the spawned entity can have the resource behavvior on it for collection

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/01f4a92a-4cbf-419a-93ec-5d03d07c4d40)

1 Node and 5 seedlings I put quantities of 5 but I always spread one as you can see

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/50dcfc26-4c59-41c5-90e3-5211e4b9527f)

**Comment by Necrym59** [comment]
@SampeyFS 
It will respawn the quantity specified but only 1 at a  time. This is the way i has to work for now as each is an individual entity with a resouce behavior attached they are not lifespan based clones.  If you want multiples - copy the resource node to create others.
By the way, this is post for your original bug issue, not for other enquiries to be added on.

**Comment by Necrym59** [comment]
@SampeyFS 
Try this version please, when NODE_TYPE is set to growth it will spawn multiple resource items. You can also set the SPAWN_SPREAD of the spawns.  When the NODE_RESOURCE_QUANTITY has been reached it will then delay for the set NODE_RESPAWN_TIME and then create a new resource node and will repeat the process.
[resource_node_v12.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15342202/resource_node_v12.zip)
Let me know how it goes.

**Comment by SampeyFS** [comment]
Ok fine thanks

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/2f901bee-bb2a-4d70-8fd9-cb57f204fd52)
Now it works but they all get shot on top of each other

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-17 141901](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/adb26b1a-ac89-4afd-ae18-912408b5ae1c)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/cf0c22d1-caf8-4bd4-87f6-1cbc3011f3a6)

**Comment by Necrym59** [comment]
@SampeyFS
Try this version 15 please.
When NODE_TYPE is set to growth it will spawn multiple resource items. You can also set the RESOURCE_SPAWN_SPREAD of the spawns. When the NODE_RESOURCE_QUANTITY has been reached it will then delay for the set NODE_RESPAWN_TIME and then create a new resource node and will repeat the process depending on how many NODE_RESPAWNS have been set. When number of NODE_RESPAWNS have been reached it will destroy the node.
[resource_node_v15.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15362915/resource_node_v15.zip)
Let me know how it goes.

**Comment by SampeyFS** [comment]
Okay thanks

**Comment by SampeyFS** [comment]
![Screenshot 2024-05-18 145622](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/3794a7ea-54c2-482c-a1c7-500f451fd462)
error?

**Comment by LeeBamberTGC** [comment]
@SampeyFS Great video showing the bug, just the kind of thing I need :)  Can you now email me the project folder that hosts that HUD screen so I can check if any corruption got in and if I can reproduce. There might be an edge case and an easy for for this one, but it does look like the hide-in-game flag is being reset before it can take effect somehow.

**Comment by SampeyFS** [comment]
[HUD Library.zip](https://github.com/user-attachments/files/15566405/HUD.Library.zip)

**Comment by LeeBamberTGC** [comment]
@SampeyFS I need the project f9older, no the HUD library folder. I need to LOAD IN the project you are working on as THAT is the part that may be corrupted.

**Comment by SampeyFS** [comment]
But all maps do, even empty ones

**Comment by SampeyFS** [comment]
That map in the video was a test map is max's original I'm not working on it was just to see if it would go the bar not even desert survival works is hidden

**Comment by LeeBamberTGC** [comment]
@SampeyFS Yes the "projectbank\the hermit of the forest" folder, thanks!

**Comment by SampeyFS** [comment]
[Uploading projectbank.zip…]()
load :-)

**Comment by LeeBamberTGC** [comment]
@SampeyFS That's the one, thanks!

**Comment by LeeBamberTGC** [comment]
@SampeyFS I found the issue :)  The tick box in the HUD editor does not matter as the scroll bar handle is dynamically shown and hidden when needed in the ingame HUD screen, that is, when you have more items than the grid is showing, ONLY THEN does the handle show up:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/09c6dba6-ccaf-4913-bd36-a942e5fe4b95)

However, there was a bug that meant you needed TWO more items over the visible collection before the handle shows up!  The fix will be in the next DEVTEST build, thanks for your persistence!

**Comment by SampeyFS** [comment]
Awesome Leee thank you too for the work I'm glad you were able to find the

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 06 04 - 20 00 42 39](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/50a09655-e031-455c-9e24-9bebf2d6f8d5)
I tried now but still hides it came out an update I tried the update but nothing @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS Send me your Max\Files\scriptbank\hud0.lua and also try adding say 5 more items to your inventory and see if the handle returns.

**Comment by SampeyFS** [comment]
[hud0.zip](https://github.com/user-attachments/files/15568660/hud0.zip)

**Comment by SampeyFS** [comment]
I tried it still gets hidden

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 06 05 - 08 42 36 18](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a0c42bcf-e0cc-495c-8f23-d081ebb44a26)


Hidden

**Comment by SampeyFS** [comment]
Can we manage to solve this problem??? @LeeBamberTGC

**Comment by SampeyFS** [comment]
The problem is always present and not solved @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS Are you using the DEVTEST branch?

**Comment by SampeyFS** [comment]
yes

**Comment by SampeyFS** [comment]
Yes but I tried the other one too, nothing changes, it does the same thing

**Comment by LeeBamberTGC** [comment]
@SampeyFS When you send me your latest standalone of your game, can you make a game save position that I can load in which shows the player having already collected 36 items, and put the player in front of a 37th item that I can pick up and then see the scrollbar not appear, thanks:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/83b681aa-4b6c-4c16-807b-1c68d4e00df9)

**Comment by SampeyFS** [comment]
Here is the save with 36 in the inventory look at loading the save there is the usual problem of lua scripts not going



DOWNLOAD -----> https://bestfile.io/en/GqZB3fOl64Gg6tL/file
________________________________
Da: Lee Bamber ***@***.***>
Inviato: domenica 23 giugno 2024 17:18
A: TheGameCreators/GameGuruRepo ***@***.***>
Cc: Studio Ascolese Games ***@***.***>; Mention ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] GGMAX Bug - Inventory scrollbar handle (Issue #5538)


@SampeyFS<https://github.com/SampeyFS> When you send me your latest standalone of your game, can you make a game save position that I can load in which shows the player having already collected 36 items, and put the player in front of a 37th item that I can pick up and then see the scrollbar not appear, thanks:
image.png (view on web)<https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/83b681aa-4b6c-4c16-807b-1c68d4e00df9>

**Comment by LeeBamberTGC** [comment]
@SampeyFS Thanks for your standalone, your game is shaping up VERY well :)  I loaded the save position you provided, then went to the fisherman shop by the lake and bought a book to make it to 37 items, and as you can see, the scroll bar appears and I can scroll down to see the new row:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/076147a3-06f3-41dd-8208-54b3ed5b4025)

**Comment by SampeyFS** [comment]
I'm happy that it helps, it's normal that my game, being ahead, outlines in the path of the mistake or the right path :-)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Also in the next DEVTEST build, I have fixed the issue with the fish going crazy when you reload. It turns out collision state was not being correctly restored:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9d10644e-91d9-4380-857a-2513e3c72882)

**Comment by SampeyFS** [comment]
I can't find the DevTest On steam invalid password dike

**Comment by SampeyFS** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d4067634-16a5-4999-a0f3-adb0f608afaf)

**Comment by LeeBamberTGC** [comment]
The DEVTEST build rotates its password, the latest one is: lettesterin42

**Comment by SampeyFS** [comment]
The inventory handle works now now the problem remains of the (lua scripts) which are not loaded when loading the save see the photos the light remains on and I was locked in the house because the door script like the others does not work


![Desktop Screenshot 2024 06 29 - 20 43 45 71](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6741b1c1-4eb5-415d-952a-cb89141d0e4f)
![Desktop Screenshot 2024 06 29 - 20 43 50 81](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/6ad0fa81-1a5d-4724-b8e3-4f2ac1abbf70)

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 06 29 - 20 43 54 22](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/a4eeff46-b84e-46bc-9114-f96e2319079a)

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you send me a save position for the standalone you have already sent me that puts me in the room with the light and door in the state you describe, then I can compare the room from a fresh new game and from loading the saved game you send me, thanks!

**Comment by SampeyFS** [comment]
All right
