### ISSUE TITLE
Selecting 'add new entity' taking too long and expanding certain folders 

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#728]
when i click on add new entity windows seems to be doing something in the background and it takes a while for the window to pop up, also certain folders are automatically expanded, i would rather have the folders collapsed by default as it use to be.

https://youtu.be/LIv482r97J4

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for your issue,

This has been fixed and will be in the next update :)

**Comment by GraPhiX-Guru** [comment]
Thank you very much Preben, and well done with all this hard work you are a star :)

**Comment by demented-mind** [comment]
Thank Preben. I was having the same issue and those 7-10 second delays can make for a long work-time on a single level.

**Comment by GraPhiX-Guru** [comment]
Hi sorry to bother you i had an update yesterday but still have this issue, i assume a new compile has not been done yet? its April now so was wondering when these latest fixes will be in a BETA or PP at the moment testing assets or creating levels is a pain :(

**Comment by plemsoft** [comment]
@GraPhiX-Guru Yes sorry @LeeBamberTGC did not put the fix into the release , but he is doing a new update this week , so hope it will be in that :)

**Comment by LeeBamberTGC** [comment]
@plemsoft Can you point me to the code change for this specific fix. I know about the IntersectAll fix that needs to go in, but if you can pinpoint the change for this one I can double check it goes into one of the quick fix updates.

**Comment by GraPhiX-Guru** [comment]
can confirm this is now fixed thank you guys :)
