### ISSUE TITLE
Entities with transparency are not displayed properly

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#832]
I found another issue that came with the latest update.

Entities with transparent textures are different now for some reason. They dont get rendered properly anymore.
Please fix it.

![Guru-MapEditor 2020-09-20 10-06-52-29](https://user-images.githubusercontent.com/35990507/93706703-09828100-fb29-11ea-9a3e-a19449afe219.jpg)
![Guru-MapEditor 2020-09-20 10-06-56-42](https://user-images.githubusercontent.com/35990507/93706704-0b4c4480-fb29-11ea-9011-8420df954258.jpg)

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for reporting this issue,

I tried a few transparent object and they worked fine ?

![transparent-2](https://user-images.githubusercontent.com/18662417/98956483-60408180-2500-11eb-8ced-77b0cd5c6f9a.jpg)

Could you e-mail me the object that dont work for you so i can test what the problem is ? : plemsoft@plemsoft.com

**Comment by Duchenkuke** [comment]
yes I will send the file.

How it should look:
![123](https://user-images.githubusercontent.com/35990507/98990509-d659de00-252a-11eb-96f9-b3b54cee462d.JPG)

how it actually looks:
![1221](https://user-images.githubusercontent.com/35990507/98990558-e5d92700-252a-11eb-8338-6f24e30f07b9.JPG)

**Comment by plemsoft** [comment]
@Duchenkuke Thanks for the sign , but it works fine here ?

![transparent-sign](https://user-images.githubusercontent.com/18662417/99039598-e8b63500-2587-11eb-9df1-e512202fc82a.jpg)

FYI: its pretty large you should set "Occluder" = no.

This problem could already have been fixed , but just in case could you sent me your .fpm , just so i can test if this is something else  , thanks :)

**Comment by plemsoft** [comment]
@Duchenkuke Ups just found the problem , you dont have transparency enabled in the fpe.

Change "transparency     = 0"
to:
"transparency     = 1"

My guess is the transparency was enabled when the dbo was generated but was then disabled (for some reasons  ? ) , 

Anyway let me know if it fix your issue , thanks :)

**Comment by Duchenkuke** [comment]
hmm strange - for me it still doesnt work. I changed the fpe and set ocludee to 0.

![Guru-MapEditor 2020-11-13 13-17-55-47](https://user-images.githubusercontent.com/35990507/99071846-33997200-25b3-11eb-9096-60d85109496a.jpg)

I zipped up the level file:
[preben_transparency test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/5536725/preben_transparency.test.zip)

**Comment by plemsoft** [comment]
@Duchenkuke ok i see its the order, Try to set "transparency = 6" to make sure its drawed last , and let me know if it fix your issue , Thanks :)

**Comment by Duchenkuke** [comment]
that fixed it, yes - strange tho as said it worked in previous version^^ well, I guess it doesnt matter 

Thank you

**Comment by plemsoft** [comment]
@Duchenkuke Yes not sure about that , could be something with the dbo ? did it not work after the current .dbo was generated ?

**Comment by Duchenkuke** [comment]
I have no idea - anyway its no problem now. thanks again
